const FolderActionTypes = {
    CREATE_FOLDER: "CREATE_FOLDER",
    ADD_FOLDER: "ADD_FOLDER",
    ADD_DURING_FOLDER: "ADD_DURING_FOLDER",
    SET_FOLDER: "SET_FOLDER",
    SET_DURING_FOLDER: "SET_DURING_FOLDER",
    CREATE_DURING_FOLDER: "CREATE_DURING_FOLDER",
    FETCH_FOLDERS_START: "FETCH_FOLDERS_START",
    FOLDER_CLEAR: "FOLDER_CLEAR"
};

export default FolderActionTypes;
