const FolderActionTypes = {
    CREATE_FOLDER: "CREATE_FOLDER",
    UPDATE_FOLDER: "UPDATE_FOLDER",
    SET_UPDATE_FOLDER: "SET_UPDATE_FOLDER",
    ADD_FOLDER: "ADD_FOLDER",
    ADD_DURING_FOLDER: "ADD_DURING_FOLDER",
    SET_FOLDER: "SET_FOLDER",
    SET_DURING_FOLDER: "SET_DURING_FOLDER",
    CREATE_DURING_FOLDER: "CREATE_DURING_FOLDER",
    FETCH_FOLDERS_START: "FETCH_FOLDERS_START",
    FOLDER_CLEAR: "FOLDER_CLEAR",
    DELETE_FOLDER: "DELETE_FOLDER",
    FOLDER_FAILURE: "FOLDER_FAILURE",
    DISABLE_FOLDER: "DISABLE_FOLDER"
};

export default FolderActionTypes;
