const TextActionTypes = {
    //text作成
    CREATE_TEXT: "CREATE_TEXT",
    ADD_TEXT: "ADD_TEXT",
    SET_TEXTS: "SET_TEXTS",
    FETCH_TEXTS_START: "FETCH_TEXTS_START",
    TEXT_FAILURE: "TEXT_FAILURE",
    CREATING_TEXT: "CREATING_TEXT",
    CLEAR_CREATING_TEXT: "CLEAR_CREATING_TEXT",
    UPDATE_TEXT_NAME: "UPDATE_TEXT_NAME",
    SET_UPDATE_TEXT_NAME: "SET_UPDATE_TEXT_NAME"
};

export default TextActionTypes;
